// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// **************************************************************************

// Generated by owl 0.2.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'errors.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

/// Mapper for PartyError
abstract class PartyErrorMapper {
  /// Converts an instance of PartyError to Map.
  static Map<String, dynamic> map(PartyError object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('status', object.code)
          ..put('title', object.title)
          ..put('detail', object.message)
          ..put('meta', ErrorMetadataMapper.map(object.metadata)))
        .toMap();
  }

  /// Converts a Map to an instance of PartyError.
  static PartyError parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final PartyError object = new PartyError();
    object.code = map['status'];
    object.title = map['title'];
    object.message = map['detail'];
    object.metadata = ErrorMetadataMapper.parse(map['meta']);
    return object;
  }

  /// Converts a JSON string to an instance of PartyError.
  static PartyError fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of PartyError to JSON string.
  static String toJson(PartyError object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

/// Mapper for ErrorMetadata
abstract class ErrorMetadataMapper {
  /// Converts an instance of ErrorMetadata to Map.
  static Map<String, dynamic> map(ErrorMetadata object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('cause', object.cause)
          ..put('details', object.details))
        .toMap();
  }

  /// Converts a Map to an instance of ErrorMetadata.
  static ErrorMetadata parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ErrorMetadata object = new ErrorMetadata();
    object.cause = map['cause'];
    object.details = map['details'];
    return object;
  }

  /// Converts a JSON string to an instance of ErrorMetadata.
  static ErrorMetadata fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ErrorMetadata to JSON string.
  static String toJson(ErrorMetadata object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
