// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// **************************************************************************

// Generated by owl 0.2.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'auth.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

/// Mapper for SpotifyToken
abstract class SpotifyTokenMapper {
  /// Converts an instance of SpotifyToken to Map.
  static Map<String, dynamic> map(SpotifyToken object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('access_token', object.accessToken)
          ..put('token_expiry', object.tokenExpiry))
        .toMap();
  }

  /// Converts a Map to an instance of SpotifyToken.
  static SpotifyToken parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SpotifyToken object = new SpotifyToken();
    object.accessToken = map['access_token'];
    object.tokenExpiry = map['token_expiry'];
    return object;
  }

  /// Converts a JSON string to an instance of SpotifyToken.
  static SpotifyToken fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SpotifyToken to JSON string.
  static String toJson(SpotifyToken object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
