// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// **************************************************************************

// Generated by owl 0.2.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'package:party/models/track.json.g.dart';

import 'party.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

/// Mapper for Party
abstract class PartyMapper {
  /// Converts an instance of Party to Map.
  static Map<String, dynamic> map(Party object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('location', object.location)
          ..put('room_code', object.roomCode)
          ..put('ended', object.ended)
          ..put('guests', object.guests?.map(GuestMapper.map)?.toList())
          ..put('current_track', PlayingTrackMapper.map(object.currentTrack)))
        .toMap();
  }

  /// Converts a Map to an instance of Party.
  static Party parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Party object = new Party();
    object.location = map['location'];
    object.roomCode = map['room_code'];
    object.ended = map['ended'];

    // ignore: avoid_as
    object.guests =
        (map['guests'] as List<dynamic>)?.map(GuestMapper.parse)?.toList();
    object.currentTrack = PlayingTrackMapper.parse(map['current_track']);
    return object;
  }

  /// Converts a JSON string to an instance of Party.
  static Party fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Party to JSON string.
  static String toJson(Party object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

/// Mapper for Guest
abstract class GuestMapper {
  /// Converts an instance of Guest to Map.
  static Map<String, dynamic> map(Guest object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('name', object.name)
          ..put('alias', object.alias)
          ..put('ckecked_in', object.checkedIn))
        .toMap();
  }

  /// Converts a Map to an instance of Guest.
  static Guest parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Guest object = new Guest();
    object.name = map['name'];
    object.alias = map['alias'];
    object.checkedIn = map['ckecked_in'];
    return object;
  }

  /// Converts a JSON string to an instance of Guest.
  static Guest fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Guest to JSON string.
  static String toJson(Guest object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
